* ARP:地址解析协议
** 1. ARP 和 RARP
http://docs.52im.net/extend/docs/book/tcpip/vol1/4/images2/52im_1.png

ARP为IP地址到对应的硬件地址之间提供动态映射。
** 2. ARP高速缓存
ARP高效运行的关键是由于每个主机上都有一个ARP高速缓存。这个高速缓存存放了
最近 =Internet= 地址到硬件地址之间的映射记录。高速缓存中每一项的生存时间一般为20分钟，
起始时间从被创建时开始算起。

使用 =arp= 可以查看
#+BEGIN_SRC bash
$ arp -a
? (192.168.1.1) at 08:10:75:c7:77:7a [ether] on ens32
#+END_SRC
** 3. 分组格式
http://docs.52im.net/extend/docs/book/tcpip/vol1/4/images2/52im_3.png
** 4. ARP代理
如果ARP请求是从一个网络的主机发往另一个网络上的主机，那么连接这两个网络的路由器就可以回答该请求，
这个过程称作委托ARP或ARP代理(Proxy ARP)。这样可以欺骗发起ARP请求的发送端，使它误以为路由器就是目的主机，
而事实上目的主机是在路由器的“另一边”。路由器的功能相当于目的主机的代理，把分组从其他主机转发给它。

实例：

http://docs.52im.net/extend/docs/book/tcpip/vol1/4/images2/52im_8.png
** 5. 免费ARP
是指主机发送ARP查找自己的IP地址。通常，它发生在系统引导期间进行接口配置的时候。

作用：
1. 一个主机可以通过它来确定另一个主机是否设置了相同的IP地址。
2. 如果发送免费ARP的主机正好改变了硬件地址（很可能是主机关机了，并换了一块接口卡，然后重新启动），
那么这个分组就可以使其他主机高速缓存中旧的硬件地址进行相应的更新。
** 6. 总结
在大多数的TCP/IP实现中，ARP是一个基础协议，但是它的运行对于应用程序或系统管理员来说一般是透明的。
ARP高速缓存在它的运行过程中非常关键，可以用arp命令对高速缓存进行检查和操作。高速缓存中的每一项内容都有一个定时器，
根据它来删除不完整和完整的表项。arp命令可以显示和修改ARP高速缓存中的内容。
