* ICMP: Internet 控制报文协议

** 1. 引言
- 位置
http://docs.52im.net/extend/docs/book/tcpip/vol1/6/images2/52im_net_1.png

- 格式
http://docs.52im.net/extend/docs/book/tcpip/vol1/6/images2/52im_net_2.png


** 2. 类型
http://docs.52im.net/extend/docs/book/tcpip/vol1/6/images2/52im_net_3.png

- 下面各种情况都不会导致产生ICMP差错报文：

1. ICMP差错报文（但是，ICMP查询报文可能会产生ICMP差错报文）。
2. 目的地址是广播地址或多播地址的IP数据报。
3. 作为链路层广播的数据报。
4. 不是IP分片的第一片。
5. 源地址不是单个主机的数据报。这就是说，源地址不能为零地址、环回地址、广播地址或多播地址。

- 这些规则是为了防止过去允许ICMP差错报文对广播分组响应所带来的广播风暴。

** 3. 地址掩码请求与应答
   ICMP地址掩码请求用于无盘系统在引导过程中获取自己的子网掩码, 系统广播它的ICMP请求报文
（这一过程与无盘系统在引导过程中用RARP获取IP地址是类似的）。无盘系统获取子网掩码的另一个方法是BOOTP协议

- 格式
http://docs.52im.net/extend/docs/book/tcpip/vol1/6/images2/52im_net_4.png

ICMP报文中的标识符和序列号字段由发送端任意选择设定，这些值在应答中将被返回。这样，发送端就可以把应答与请求进行匹配。

** 4. ICMP时间戳请求与应答
   ICMP时间戳请求允许系统向另一个系统查询当前的时间。返回的建议值是自午夜开始计算的毫秒数，
协调的统一时间（Coordinated Universal Time,UTC）。这种ICMP报文的好处是它提供了毫秒级的分辨率，
而利用其他方法从别的主机获取的时间（如某些Unix系统提供的rdate命令）只能提供秒级的分辨率。
由于返回的时间是从午夜开始计算的，因此调用者必须通过其他方法获知当时的日期，这是它的一个缺陷。

- 格式
http://docs.52im.net/extend/docs/book/tcpip/vol1/6/images2/52im_net_6.png

请求端填写发起时间戳，然后发送报文。应答系统收到请求报文时填写接收时间戳，在发送应答时填写发送时间戳。
但是，实际上，大多数的实现把后面两个字段都设成相同的值

** 5. ICMP端口不可达差错
- ICMP不可达报文的一般格式
http://docs.52im.net/extend/docs/book/tcpip/vol1/6/images2/52im_net_17.png
