* IP 选路
** 1. IP 层工作流程
http://docs.52im.net/extend/docs/book/tcpip/vol1/9/images2/52im_net_1.png
** 2. 原理
- IP搜索路由表的步骤
  1. 搜索匹配的主机地址
  2. 搜索匹配的网络地址
  3. 搜索默认表项（默认表项一般在路由表中被指定为一个网络表项，其网络号为0）
*** 2.1. 路由表
#+BEGIN_SRC bash
$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 ens32
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 ens32
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-278c5378a8e5
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 ens32
#+END_SRC

- 对于一个给定的路由器，可以打印出五种不同的标志（flag）：
  - U 该路由可以使用。
  - G 该路由是到一个网关（路由器）。如果没有设置该标志，说明目的地是直接相连的。
  - H 该路由是到一个主机，也就是说，目的地址是一个完整的主机地址。如果没有设置该标志，说明该路由是到一个网络，而目的地址是一个网络地址：一个网络号，或者网络号与子网号的组合。
  - D 该路由是由重定向报文创建的
  - M 该路由已被重定向报文修改
** 3. ICMP主机与网络不可达差错
当路由器收到一份IP数据报但又不能转发时，就要发送一份ICMP“主机不可达”差错报文
** 4.  ICMP重定向差错
当IP数据报应该被发送到另一个路由器时，收到数据报的路由器就要发送ICMP重定向差错报文给IP数据报的发送端,
而源主机就可以利用这个信息来更新自己的路由表,这样,随着网络通信的逐渐增多,路由表也就越来越完备,数据转发的速度也会越来越快

注意：
- 重定向报文只能由路由器发出。
- 重定向报文为主机所用,而不是为路由器所用。
** 5. 路由发现
在主机引导的时候,一般会发送在网内广播一个路由请求的 ICMP 报文,而多个路由器则会回应一个路由通告报文。
而且,路由其本身不定期的在网络内发 布路由通告报文,这样,根据这些报文,每一个主机都会有机会建立自己的
路由表而实现网络通信。路由 器在一份通告报文中可以通告多个地址,并且给出每一个地 址的优先等级,
这个优先等级是该 IP 作为默认路由的等级
